### ISSUE TITLE
Remove external dependencies - gpg

### ISSUE THREAD

**Issue by dominikschulz** [justwatchcom/gopass#154]
It would be nice if we could get rid of our external dependencies some day.
This would allow for a nicer workflow, better error and cross platform support.
This issue is meant to track any progress / discussions on that matter for gpg.

**Comment by dominikschulz** [comment]
* https://godoc.org/golang.org/x/crypto/openpgp - The "official" PGP package by the Go authors, seems to be a little neglected and has some outstanding bugs, e.g. Secret Keyring parsing is flaky at best

**Comment by yml** [comment]
I did exactly this in [my own password management lib](https://github.com/yml/keep) but now I am in dead end since golang openpgp does not support modern version of gnupg version above 2.1.

* https://github.com/mozilla/sops/issues/189
* https://github.com/oleiade/serrure/issues/6
* https://github.com/yml/keep/issues/1

**Comment by bkcsoft** [comment]
For Gitea we use https://github.com/keybase/go-crypto/tree/master/openpgp instead of `x/crypto/openpgp` since we wanted support for new and shiny keys 🙂

**Comment by yml** [comment]
@bkcsoft do you have an example on how to make it work with gpg agent ?

**Comment by jungle-boogie** [comment]
It would still be an external dependency, but it's much more of a lightweight dependency:
https://github.com/tarsnap/scrypt
