### ISSUE TITLE
Doc Update Proposal: How to validate an imported pubkey with gpg ( `recipient add` requires valid keys ) 

### ISSUE THREAD

**Issue by frntn** [justwatchcom/gopass#256]
# Context

I wanted to add a newly imported gpg pubkey but got an error : 
```
frntn@xoqnap:~$ gopass recipients add E80A281C00A03D2D --store team-devel

Error: no matching valid key found in keyring
```

Turns out the key validity is **unknown** 
```
frntn@xoqnap:~$ gpg --edit-key E80A281C00A03D2D quit 
gpg (GnuPG) 1.4.20; Copyright (C) 2015 Free Software Foundation, Inc.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

pub  4096R/00A03D2D  created: 2017-08-09  expires: never       usage: SC  
                     trust: unknown       validity: unknown
sub  2048R/82BF1BAC  created: 2017-08-09  expires: 2025-08-07  usage: E   
sub  2048R/8141E4E8  created: 2017-08-09  expires: 2025-08-07  usage: SA  
[ unknown] (1). Hamid Abdoul <hamid.abdoul@gmail.com>
```

And I believe this makes sense : the `alwaystrust` is applied when encrypting secret for users already added in the store, so _already trusted by one of the team member..._

# Proposal 

May be you could help in the process of validating a key by mentioning somewhere in the documentation the following options : 

- your key : ultimately trust it => `gpg --edit-key [keyid] trust quit        # set to "ultimate" (5)  `   
- others key : sign it => `gpg --edit-key [keyid] sign save quit`

**Comment by dominikschulz** [comment]
You're right, this is in inconsistency between `recipients add` and our handling of `alwaysTrust`.
As we (currently) always enable `alwaysTrust` we shouldn't reject keys with `unknown` trust.

Also we should document how to edit the trust.

Maybe we could still check for unknown keys when running `gopass recipients add` but instead of rejecting unknown keys we could print the info how to make them valid but still add them?
