### ISSUE TITLE
What is the correct config file?

### ISSUE THREAD

**Issue by adius** [justwatchcom/gopass#311]
The readme talks about `~/gopass.yml` and `~/.config/gopass/config.yml`.
Which one is correct?

**Comment by dewey** [comment]
Both are correct as it tries to read the configuration file from multiple default locations [1]. It should probably be consistent in the documentation to avoid confusion though.

[1] https://github.com/justwatchcom/gopass/blob/8ef89b3a59ced0db61474045a19979a70b1bf1f9/config/config.go#L126

**Comment by adius** [comment]
I'd propose using `~/.config/gopass/config.yml` as the default and `~/gopass.yml` as the fallback.

Actually you should also check for `{config,gopass}.yaml`, as it is the official file extension for YAML files:
http://www.yaml.org/faq.html

**Comment by dominikschulz** [comment]
The correct location is `~/.config/gopass/config.yml`. We support `~/.gopass.yml` (note the dot) as a fallback, since that used to be the default in the past.

I don't want to support different extensions as well. There is a nice CLI interface (`gopass config`) to edit the config, I don't really expect users to edit the config directly.

If I would have been aware of this FAQ entry I would have chosen `.yaml` in the first place, but I don't see any point in supporting both.

Closing this issue once the docs are updated.

**Comment by adius** [comment]
> If I would have been aware of this FAQ entry I would have chosen .yaml in the first place, but I don't see any point in supporting both.
😭 ... but yeah supporting both is probably not a good idea

gopass should print a warning if you have both files (like I did 🙄)

**Comment by dominikschulz** [comment]
Updated the docs.

I considered checking for `.yaml` files as well, but I think the use case wouldn't justify adding a bunch of (possibly) buggy code just to print a warning.

If someone comes up with a clean way to check and warn feel free to open an PR.

**Comment by adius** [comment]
Oh no, I meant printing a warning if both `~/.gopass.yml` and `~/.config/gopass/config.yml` exist!
(although a warning if a  .yaml exists make sense as well ...)

Btw @dominikschulz: You should fix your gif configs! "dominikschulz committed with dominikschulz" sounds a little stupid =P

**Comment by dominikschulz** [comment]
Either way, I don't see a clean way to do that right now. If someone does, feel very welcome to submit a PR.

Don't worry about my git config, it's intentional.
