### ISSUE TITLE
pull before tree/find

### ISSUE THREAD

**Issue by SevereOverfl0w** [justwatchcom/gopass#320]
https://github.com/justwatchcom/gopass/issues/281#issuecomment-324937685

In a similar vein to this comment. It would be useful to attempt to do a `git pull` before `gopass search` & such.

This would make it easier to transparently operate in a team.

**Comment by dominikschulz** [comment]
We were considering this before, but so far I think this might be too slow/expensive.

We may consider doing that if a search yields no results, but if we do it on every operation (even if only on `search`) that would incur a sever latency that some people (including me) are not willing to pay.

**Comment by falschparker82** [comment]
Agree that it's well-intentioned, but probably a bad idea overall. 
Especially since it opens a lot of new corner cases - like a connection interruption (or air-gapped server) blocking showing the tree, while you _just want_ to access the damn secret because you know it's downloaded already.

There's a few milder versions that are more promising IMHO, food for thought:
1) Simple new short flag that shouldn't collide with any existing so far (haven't checked TBH), like `gopass search -p foo` or `gopass tree -p` will pull before executing
2) Kicking off a simple (and hopefully fast) comparison with upstream in a background goroutine, with a timeout and waiting for either upstream fetch or that short timeout (maximum maybe 2s), displaying a message after the command: "Newer upstream version detected, type `gopass pull && !!` to update"
3) A combination of the above

**Comment by dominikschulz** [comment]
@SevereOverfl0w Do you think the new `gopass sync` command could be useful for your usecase? It's not yet in any release, but we're trying to publish an release candidate soon.

**Comment by SevereOverfl0w** [comment]
I definitely think it could help.
I'm slightly on the fence with this one, because of the problems you highlighted.
This might be something for tooling to solve (e.g. The various browser integrations can offer a helpful sync button).
I'm mostly trying to minimize friction for people who may irregularly use this tool in a team such that I don't get a "The password is missing, halp"
I do like the suggestion of sync on a failed find, but accept this makes the tool more complex.
-------- Original message --------From: Dominik Schulz <notifications@github.com> Date: 12/09/2017  12:13  (GMT+00:00) To: justwatchcom/gopass <gopass@noreply.github.com> Cc: Dominic Monroe <monroef4+github@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [justwatchcom/gopass] pull before tree/find (#320) 
@SevereOverfl0w Do you think the new gopass sync command could be useful for your usecase? It's not yet in any release, but we're trying to publish an release candidate soon.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/justwatchcom/gopass","title":"justwatchcom/gopass","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/justwatchcom/gopass"}},"updates":{"snippets":[{"icon":"PERSON","message":"@dominikschulz in #320: @SevereOverfl0w Do you think the new `gopass sync` command could be useful for your usecase? It's not yet in any release, but we're trying to publish an release candidate soon."}],"action":{"name":"View Issue","url":"https://github.com/justwatchcom/gopass/issues/320#issuecomment-328821289"}}}

**Comment by dominikschulz** [comment]
As a possible workaround that is less intrusive I've added a "sync" hotkey to the selection wizard. Hope that helps. Still don't want to run sync/pull on every search.
