### ISSUE TITLE
Define handling of linebreaks

### ISSUE THREAD

**Issue by dominikschulz** [justwatchcom/gopass#348]
So far gopass does not specifically handle / transform line breaks. When using gopass across several platforms we may need to actually convert these similar to how FTP does.

See #344

**Comment by frntn** [comment]
My statement in #344 regarding this FTP-like feature was just my guess of what you tried to achieve with the default (non-binary) behavior.
But I don't consider this approach to be a good design for gopass.

IMO you shouldn't convert anything (git does not perform that kind of conversion at all for example)
**File integrity cannot be an option : Hashes before and after *must* be the same**

cc @metalmatze ?

----
**_Side note :_** 
Playing with pipes (`|`) or redirects (`<`, `>`) on UNIX-like OSes doesn't require to know if we are dealing with binary files or text files. Same must apply with gopass. 
I don't believe the `binary` subcommand makes sense at all because git and gpg are able to handle blobs and doesn't require base64 conversions : every gopass subcommands has to deal in binary mode.
_(I'd rename the `binary` subcommand to `base64` subcommand for backward compat)_

**Comment by falschparker82** [comment]
I also have a super bad feeling about this - looks like in the name of trying to be helpful, this could enable all kinds of weird and unexpected behavior. By the Unix philosophies of "Rule of Least Surprise / Rule of Robustness", I'd strongly refrain from this kind of stuff. `cat`ing a secret into a file should yield exactly the same result as pasting it on screen.

It means introducing logic where it's not needed, making things more complex, more dangerous while being semi-helpful.

Remember scripting is something for advanced users. If they have a problem wielding `tr -d '\n'`, they probably shouldn't be scripting at all. The farthest I would go with this would be introducing a command line parameter for *explicit* enabling of this feature.

**Comment by frntn** [comment]
I couldn't have explained it more clearly :smile:

**Comment by metalmatze** [comment]
Let me elaborate on why we've created the `binary` command:
We want to be backwards compatible to _pass_. When we first started talking about the feature of storing binary data with gopass, we had exactly that in mind. What happens if you store some binary data with gopass but someone else opens the file with pass. You'd get a bunch of nonsense printed to your screen. That's why we decided to go with converting binary data to base64. That way opening a file in another compatible password store doesn't actually print nonsense, but rather a long string.

That's just the train of thought we had and should explain why it's currently implemented like this.
I'm not really sure what's best for the future now. Should we try to stay as much compatible to the original pass, or should we start to do our own thing with binaries?

**Comment by falschparker82** [comment]
Is this discussion related to the binary feature at all? My thought would have been that binary is binary and stays binary? No need of handling any linebreaks there as you wouldn't paste it on the terminal anyway? (well, or regretting it ^^)

**Comment by dominikschulz** [comment]
No so fast, I was only suggesting that we think about how (and if) we want to handle different line breaks on different platforms and document that.

No necessarily that we do so.

Furthermore I've tried to implement the binary feature as @falschparker82 designed it. Do you think it's not like you imagined it?

Also we don't (and IMHO can't) guarantee that everything piped into gopass is output unaltered. We already have too many cornercases (like YAML, etc.). That's one of the reasons for the binary/base64 feature.

Please try to focus on the making a decission about handling linebreaks and this issue and raise additional issues for other topics, if necessary!

**Comment by metalmatze** [comment]
Sorry if I mixed things up.

**Comment by falschparker82** [comment]
I wasnt't complaining at all about the binary feature, I just wanted to suggest it's not relevant to this discussion :)

**Comment by dominikschulz** [comment]
Ok, thanks for clarifying. Wasn't sure in the first place.

**Comment by dominikschulz** [comment]
We definitely need documentation and integration/unit tests defining our desired behaviour before closing this issue.

**Comment by dominikschulz** [comment]
As long as nobody comes up with a good usecase and a compelling user story, we should probably agree to not alter the secret content in any way, i.e. we should not try to convert any line breaks.

If no one objects, I'd close this issue after this fact has been properly documented.
