### ISSUE TITLE
Gopass should offer to install GPG2 for you

### ISSUE THREAD

**Issue by Zamiell** [justwatchcom/gopass#485]
Currently, on a default Ubuntu 16.06 installation, running gopass gives the following warning:

```
Warning: Using GPG 1.x. Using GPG 2.0 or later is highly recommended
```

Since Ubuntu 16.06 is one of the most common operating systems in the world (with respect to gopass' intended audience), this is probably something that gopass should automatically take care of for you.

Like something along the following:

```
Warning: Your version of GPG is 1.4.20. Using GPG 2.0 or later is highly recommended.
Do you want to install it? [Y/n]
```

So for this feature to work the code would need to detect the operating system archetype. I think it is sufficient to provide logic here for the 3 most common situations:

* Debian/Ubuntu - `sudo apt install gnupg2 -y`
* RHEL/CentOS - `sudo yum install gnupg2 -y`
* macOS - `brew install gnupg2`

**Comment by dragon788** [comment]
Ideally software shouldn't force an implementation on you if it isn't necessary, ie if it works with gpg1 and gpg2 they should just offer the message they have without forcing you to change.

One of the things I most enjoy in FOSS is that there are many ways to accomplish something, but a common anti-pattern is hardcoding a decision and trying to support an ever expanding matrix of package managers and packages that aren't absolutely required but are suggested and this often bogs down developers in the minutia of specific platforms and packaging decisions rather than improving the product they work on.

With that said, since the code is open it shouldn't be hard to add a "suggests" or "recommends" per the Debian Packaging Handbook to the keybase.deb file that proposes gpg2 if the user doesn't have either version, but uses gpg1 if present, and I'd imagine this is already there.

On macOS I believe that `brew install gnupg` is also defaulting to `gnupg2` now, and this is one of those minutia that tends to confuse the issue if your primary development environment doesn't match the users environments but accounting for every possibility is a lot of overhead without a good CI pipeline.

**Comment by dominikschulz** [comment]
I don't think installing dependencies should be part of `gopass`. This is something that should be handled by whatever installation method the user chooses.

If someone builds from source he will have to take care for that himself, for other methods we should try to make it easy to do the right thing (i.e. adding `suggests` to the debian packages).

**Comment by Zamiell** [comment]
Sounds reasonable. So lets add the suggestion to the Debian packages.

On yum however, is it possible to add a "suggested" package? [This page](https://unix.stackexchange.com/questions/57524/yum-and-recommended-suggested-packages) seems to indicate that it is not possible. So it might be better to set gnupg2 as a required package here.

Finally, regardless of whether or not gopass automatically installs packages for you, I think it would be a nice touch to make the warning message a little better.

```
Warning: Using GPG 1.x. Using GPG 2.0 or later is highly recommended
```

-->

```
Warning: Your version of GPG is 1.4.20. Using GPG 2.0 or later is highly recommended. This can be installed via the "gnupg2" package on most platforms.
```
(printing the exact version)

**Comment by dominikschulz** [comment]
That sounds reasonable, we'll add the gpg2 suggests / recommends for debian, the depends for RPM and change the warning message.

**Comment by dominikschulz** [comment]
Changed the depends to `gnupg2`, should be available on all supported platforms.
