### ISSUE TITLE
Yaml parsing assumes nested values for non-string types

### ISSUE THREAD

**Issue by martinhoefling** [justwatchcom/gopass#559]
Assume you have  a secret in the following form:

``` yaml
mypassword
---
user: 1234
url: http://my.url.com
```

The user yaml value cannot be obtained since gopass is complaining about nested values. This is due to the [interface assertion in secret.go](https://github.com/justwatchcom/gopass/blob/c5a8e526ed0066909e47d7985d4675c433378d0a/store/secret/secret.go#L149). Non string types, like bool, float and int are not covered here.

Several fixes are thinkable:

1. parse with regexp instead of yaml. This would be robust but would prevent extending yaml features in the future.
2. implement conversion to string in the yaml parser. That would make it a string independent on the method you're using to access the value. It also works with values like
3. Extend the `Value` method to support other types. That would work out for most cases but e.g. the conversion to float and back to string could suffer from concatenation: `1.23400` would translate to `1.234` which is probably no transparent to the user. Same goes for 0815
4. We can also leave it as it is but make clear to the user that those special values must be put in double quotes.

What are your thoughts? I would go for 2. or 3. and can pick up the issue if desired.

**Comment by dominikschulz** [comment]
The problem is that most people don't understand YAML. And they shouldn't have to. The question I'm asking myself is if it's better have proper YAML support or a proper UX. I'd go for UX here.

IMHO what we should do is to think about dropping the YAML parser. Parsing key-value pairs should be easy and robust even without regexp. I'd only need to think about marshaling and handling of more complex data for a moment, e.g. we use YAML folded style/heresocs in a few secrets.

**Comment by martinhoefling** [comment]
Just as reference:
Problematic cases are 

```yaml
mypassword
---
user: 1234.131100
```
If you parse as number, you end up with `1234.1311` as username which is probably wrong for most users.

**Comment by dominikschulz** [comment]
Thanks for the example. I fully aware of the nature of this problem. I'm just not sure on what the best approach would be.

**Comment by dominikschulz** [comment]
See also #659
