### ISSUE TITLE
gopass for my Android

### ISSUE THREAD

**Issue by oren** [justwatchcom/gopass#571]
I am currently using [Kpcli](http://kpcli.sourceforge.net/) for ubuntu and [Keepass2Android](https://play.google.com/store/apps/details?id=keepass2android.keepass2android&hl=en) for my Android and they use the same format so I can share them on Dropbox.

It looks like gopass is not an alternative since it's only going to work on my laptop. Are there any plans to also have a mobile (or mobile web) solution?

**Comment by dominikschulz** [comment]
AFAIK some people use pass-compatible apps on Android. Maybe @metalmatze can help.

**Comment by metalmatze** [comment]
Yes. I am using https://play.google.com/store/apps/details?id=com.zeapo.pwdstore for over a year now and its compatible with gopass.
It uses git to synchronize all files.

**Comment by oren** [comment]
fantastic! I'll give it a try.

**Comment by oren** [comment]
i would like to recommend this to my friends. is there also a version for iphone, Mac, and Windows?

**Comment by dominikschulz** [comment]
`gopass` is confirmed to work on Linux and Mac. The maintainers and many contributors use either one of these platforms. Windows is known to work, but it depends a lot on the exact environment (cmd.exe, PowerShell, cygwin shell, bash for windows, ...). There should be a compatible iPhone app, but I'm not sure if it works.

**Comment by oren** [comment]
got it. thanks!

**Comment by zonArt** [comment]
Hi, I found this question while looking for some information on how to use gopass and Android and wondered if the mentioned application supports the yubikey to store the gpg keys

**Comment by martinhoefling** [comment]
For iPhones, I can recommend [pass for](https://github.com/mssun/passforios) IOS. It's pass compatible and only supports one store (git repo) but otherwise works fine in my gopass setup.

**Comment by metalmatze** [comment]
> Hi, I found this question while looking for some information on how to use gopass and Android and wondered if the mentioned application supports the yubikey to store the gpg keys

@zonArt, the Android App works with YubiKeys indeed! I use it every second day on my OnePlus3 with a YubiKey 5C.

**Comment by glowinthedark** [comment]
in fact you can use `gopass` as-is directly on your android:

1. install and init [Termux](https://f-droid.org/en/packages/com.termux/) ([github repo](https://github.com/termux/termux-app))
2. install gopass with `apt install gopass gnupg openssh`
3. [optional, just for fun] install the original `pass` and otp support with `apt install pass pass-otp`
4. [optional, for better usability] install [Termux Widgets](https://wiki.termux.com/wiki/Termux:Widget) ([F-Droid](https://f-droid.org/en/packages/com.termux.widget/)) and [Termux API](https://wiki.termux.com/wiki/Termux:API) ([F-Droid](https://f-droid.org/en/packages/com.termux.api/)) so that you can add shortcuts directly to your android desktop and get a password or an OTP token with a single tap. After installing the API package, and running `pkg install termux-api` from within termux you'll be able to use e.g. `gopass mysecret42 | termux-clipboard-set` and add it as an executable script to the `~/.shortcuts` folder — now you can add the termux widget to your desktop and generate an otp token or get a password automatically copied to the clipboard. Termux Widgets can expose either single scripts or a list of all scripts under `~/.shortcuts` as seen below (screenshot from the [termux widget repo](https://github.com/termux/termux-widget)):

<img height="240" src="https://raw.githubusercontent.com/termux/termux-widget/refs/heads/master/termux-widget.png"> 


> <sup>You can copy your `~/.ssh` folder from your desktop and everything will work as expected, including the aliases you have in your `~/.ssh/config` (just make sure you `apt install openssh` which includes the `ssh` client).</sup>

---

As an alternative, you can also build the current `master` branch of `gopass` under termux:

```bash
pkg i golang 
## this currently installs go v1.18

go install github.com/gopasspw/gopass@latest
```

**Comment by AnomalRoil** [comment]
I'm using https://github.com/android-password-store/Android-Password-Store on my side and it works well on Android and supports Yubikeys / hardware token through [OpenKeyChain](https://www.openkeychain.org/) and even displays key-values entries properly.

**Comment by glowinthedark** [comment]
Also using [Android-Password-Store](https://github.com/android-password-store/Android-Password-Store) BUT the app only supports a single repo + single GPG key and there are no plans to implement multiple repos (my use case). That's why I settled on using the app for my main store and `gopass` in termux for the additional stores.

**Comment by N7K4** [comment]
> Yes. I am using https://play.google.com/store/apps/details?id=com.zeapo.pwdstore for over a year now and its compatible with gopass. It uses git to synchronize all files.

The link is broken :-( Or the app is not anymore listed

**Comment by glowinthedark** [comment]
@N7K4: the current play store and f-droid links are in the [git repo](https://github.com/android-password-store/Android-Password-Store#download)

**Comment by einsiedlerkrebs** [comment]
Sure! My question wasn't precise: Are people from the gopasswd community plan to close the gap on Android.

**Comment by freijon** [comment]
I created this script for myself after the Android Password-Store was archived. Version 2.x was going in a direction that I didn't like anyway.

## How it works
When you run `pw` your passwords will be selectable with `fzf`. It will then copy the *username* to the clipboard for 5sec, then the password for 20sec, then clear it. The idea is to switch to the other app in the mean time and paste the information. If you run `pw -s` it will do the same, but only display all key/values in tabular form instead of copying. 
It's not as nice as Auto-Fill but still quite fast and provides a good enough workflow for me. 

## Requirements
- nushell (`pkg install nushell`, or: feel free to translate the code below to bash or whatever 😁)
- gopass (`pkg install gopass`) 
- fd (`pkg install fd`, but you could also use `find`)
- fzf (`pkg install fzf`)
- Termux API

## Nushell Code
Feel free to use / modify as you like. 

```nushell
def pw [
  query?: string # Optional search term to pre-filter password entries
  --show (-s)    # Flag to display credentials instead of copying to clipboard
] {
  # Set default query to empty string if not provided
  let query = ($query | default "")

  # Find password files, strip path and extension, then let user select with fzf
  let password_file = (
    fd -t f --color=always . ~/shared/.password-store/
    | str replace -a /data/data/com.termux/files/home/shared/.password-store/ ''
    | str replace -a ".gpg" ""
    | fzf --keep-right --ansi --query $query
  )

  # Handle case when user cancels selection
  if ($password_file | is-empty) {
    print "No password selected"
  }

  # Retrieve credentials from password store
  let raw_credentials = (gopass show $password_file | lines)
  if ($raw_credentials | is-empty) {
    print "Failed to retrieve credentials"
  }

  # Extract password (first line) and parse remaining lines as key-value pairs
  let credentials = {
    password: $raw_credentials.0
    parsed: ($raw_credentials 
      | skip 1 
      | parse "{key}:{value}" 
      | str trim
      | where key != "" and value != ""
    )
  }

  # Build a complete record with password and all parsed fields
  let record = ($credentials.parsed 
    | reduce -f {password: $credentials.password} {|item, acc| 
        $acc | insert $item.key $item.value
      }
    | sort
  )

  if $show {
    # Display all credentials in tabular format
    $record
  } else {
    # Verify username exists before attempting to copy
    if ($record | get -i username) == null {
      print "No username found in credentials, copying password"
    } else {
      # Copy username to clipboard with notification
      $record.username | termux-clipboard-set
      termux-toast "Username copied"
      sleep 5sec
    }
    
    # Copy password to clipboard with notification
    $record.password | termux-clipboard-set
    termux-toast "Password copied"
    sleep 20sec

    # Clear clipboard for security
    "" | termux-clipboard-set
    termux-toast "Clipboard cleared"
  }
}
```

**Comment by yzx9** [comment]
A small self-plug for anyone who lands on this issue looking for an Android client without having to run the CLI inside Termux, or for a more gopass-oriented option alongside Android-Password-Store:

I built [**gpm**](https://github.com/yzx9/gpm), a modern Android-first gopass client: https://github.com/yzx9/gpm

It supports existing **age and GPG/OpenPGP** gopass stores, Git sync, search, history, and creating/editing secrets.

I’m also working on Autofill support. The core is cross-platform, so iOS should be possible too — contributions are very welcome if anyone is interested!

Still early, but already usable. Feedback is very welcome :)

**Comment by dominikschulz** [comment]
@yzx9 Thanks for sharing. This looks really cool. I'll check it out and if I see no issues we'll definitely point our users to that as well.
