### ISSUE TITLE
Use gpg2 if available

### ISSUE THREAD

**Issue by mzur** [justwatchcom/gopass#6]
pass uses gpg2 instead of gpg if it is available:

```shell
GPG_OPTS=( "--quiet" "--yes" "--compress-algo=none" "--no-encrypt-to" )
GPG="gpg"
export GPG_TTY="${GPG_TTY:-$(tty 2>/dev/null)}"
which gpg2 &>/dev/null && GPG="gpg2"
```

It looks like gopass always uses [just gpg](https://github.com/justwatchcom/gopass/blob/a0d8412e422d8951c5da4bab40545fb8089cd081/gpg/gpg.go#L298). IMHO it should also switch to gpg2 if it is available so it behaves exactly like pass.

I'd do a PR but unfortunately I'm not very familiar with Go (yet).

**Comment by metalmatze** [comment]
I think that went missing in the process of writing too. We should do that. Yep! 

Thanks for reporting.

**Comment by Xylakant** [comment]
This also makes it fail for smartcard based workflows on systems that rely on pcscd since gpg1 starts an agent that can't handle the smartcard connection.

**Comment by metalmatze** [comment]
@Xylakant I don't really get if this is still a problem, now that #9 is merged.

**Comment by Xylakant** [comment]
@metalmatze I did a test-build with the current develop and it doesn't have the problem. I just wanted to record that, so other people with the same problems can find it in the tracker.

**Comment by mikeatm** [comment]
Hmm, for some users (read me), the distinction between `gpg` and `gpg2`  was unclear, and i had keys listed by  `gpg` but not `gpg2` (creating on one does not seem to get them viewable from the other), so newer versions of `gopass`  seemed broken until i figured this out. could someone suggest some support for informing users who have both `gpg` and `gpg2`,  since its not obvious which of the two has their private keys.
