### ISSUE TITLE
key value with multiword values gives error

### ISSUE THREAD

**Issue by deltaskelta** [justwatchcom/gopass#606]
I am on MacOS and when I create a new secret and I get to the key-value step, I cannot seem to enter multi word values. I can't see any reason for this in the go code as it seems the `askForString` should take multi word values...

```
Enter zero or more key value pairs for this secret:
Name for Key Value pair (enter to quit) []: comment
Value for Key 'comment' []: this ia ^H^Hcomment
```

I have also noticed that I cannot use backspace when it is asking me for inputs so I am not sure if this is a related issue, it seems it might be...

Any idea what is going on?

**Comment by dominikschulz** [comment]
Actually yes, at least if you built from a recent master branch. There was a change to the input handling that will only allow entering one word per line. This should for most/all cases but it's rather a workaround. Will look into this.

**Comment by dominikschulz** [comment]
I just tried to reproduce this (on Linux, though):
- 1.6.6 - Works as expected (Backspace and Multi-Word Values)
- 1.6.7 - `gopass create` is broken, will be fixed in 1.6.8 (coming soon)
- master (8bce34a2) - Works with the restriction described in https://github.com/justwatchcom/gopass/issues/606#issuecomment-355488648, i.e. Backspace works, multi-word values don't . Will try to fix that for 1.6.8

Could you please attach the output of `gopass version`?

**Comment by dominikschulz** [comment]
The multi-word issue should be fixed. Please open another issue if the backspace issue keeps bothering you.

**Comment by deltaskelta** [comment]
gopass version:
```
gopass 1.6.7-git+HEAD go1.9.2 darwin amd64
  GPG: 2.2.4
  Git: 2.15.1
```
