### ISSUE TITLE
Inability to use gopass programmatically

### ISSUE THREAD

**Issue by qbit** [justwatchcom/gopass#640]
Currently when doing something like `gopass show entry-that-does-not-exist` gopass will drop users to a wizard UI, this prevents other tooling from using gopass programmatically.

For example [this](https://github.com/gcoop-libre/ansible-lookup-plugin-pass/) tool lets ansible use pass compatible tools to manage passwords on remote systems. However, gopass hangs when running `show` on a non-existing password.

**Comment by metalmatze** [comment]
This also applies when setting -f as a flag, said @qbit on matrix Chat.

**Comment by qbit** [comment]
I have a diff that lets users completely disable the UI: http://ix.io/EFG/diff

It fixes the issue - but I don't know if it's the right approach. Maybe detection of execution mode would be a better way to decide if the UI should be displayed.

**Comment by dominikschulz** [comment]
The UI wizards should only be displayed if gopass is running in a terminal.
Here is the detection: https://github.com/justwatchcom/gopass/blob/master/context.go#L62
This is where the value is used: https://github.com/justwatchcom/gopass/blob/master/action/show.go#L107

For me it works. Maybe it's a platform specific bug? Otherwise I'd need more info to reproduce, please.

**Comment by qbit** [comment]
I have no idea why I hit this.. I can't reproduce.. Everything is working fine.. Sorry for the noise!
