### ISSUE TITLE
Displaying password history

### ISSUE THREAD

**Issue by kepi** [justwatchcom/gopass#655]
I'm not able to find documentation about any way how to display "password history". If I checkout some git revision in past, I'm able to show previous password, but it is pretty unfriendly way.

Is there such possibility already and I'm blind only?

If not, would you consider adding it? I believe that password history is important feature of any password manager and saved my day many times with keepass.

Today I hit one of typical use cases - you need to change password on some system and it asks old and new password. How to do that wth gopass comfortably?

Another one is displaying all past passwords for some entry with dates when they were replaced.

**Comment by dominikschulz** [comment]
Right now there is no support for this at all, but it sounds like a very useful addition.

If we find a good way to implement this, I'd be happy to add this feature. I don't know if I'll be able to work in this anytime soon, so a PR would be very well received. Otherwise I'll try to look into this eventually.

**Comment by dominikschulz** [comment]
@kepi @dewey Please have a look at #660 and let me know if that's what you were thinking of or not.

**Comment by kepi** [comment]
Finally found time to test it, working just fine. Huge thanks!
