### ISSUE TITLE
Disable copy to clipboard after generate

### ISSUE THREAD

**Issue by swalladge** [justwatchcom/gopass#667]
The current behaviour (version 1.6.10) seems to be that it copies the generated password to the clipboard after generating it with `gopass generate <name>`. This behaviour is undesirable because it gets picked up and stored by most clipboard managers.

Some alternatives could be:

- only copy to primary selection which most password managers don't (or can be configured to not) store.
- disable copying to clipboard altogether and let the user manage it

**Comment by dominikschulz** [comment]
Thanks for bringing this up.

Unfortunately I'm not sure what to do about this. There are different opinions about the default behavior wrt. the clipboard. Personally I don't really care too much, but I don't want to change this back and forth.

In #410 there was the justified request to not display the password by default and we implemented that.
If we now change it back the reporter will probably complain. If we neither copy it to the clipboard nor display it others (including me) will complain because it would be a lot more annoying.

Unfortunately copying the password to the primary area would only work on Linux and the libs we're currently using don't support it (see #477).

So actually I'm in favor of keeping the default as-is. You can either use the `--print` flag or we could consider adding a config option for this.

Also please note that gopass at least tries to erase the clipboard managers history.

**Comment by swalladge** [comment]
Agreed, I don't mind that as the default behaviour. But a configuration option would be nice, because at the moment, I'm going to end up with passwords sitting around in my plaintext clipboard manager's history (clipster) if I forget to manually delete them....

I'm also happy to work on a pr sometime. :)
