### ISSUE TITLE
Displaying Incorrectly in Tmux

### ISSUE THREAD

**Issue by stevesbrain** [justwatchcom/gopass#759]
Hi all,

Not sure if this is an issue specifically that affects me, or if it affects other tmux users. Long story short, using the same terminal (urxvt) [with tmux](https://asciinema.org/a/aEJe8ZQkIpeWwColVAXPjY4Px) produces illegible output, and [without tmux](https://asciinema.org/a/B43WSI5ZBjUwVYTskUUY3cEsT) produces completely fine output. 

Although the asciinema recording of the tmux version is not a 100% accurate representation of what I see, it's fairly close (and does demonstrate how illegible it is) - let me know if you want a proper screen recording :) Any assistance is appreciated!

**Comment by stevesbrain** [comment]
Just a follow up - it's *slightly* better in xterm than it is in urxvt, but not drastically different. Still broken when attempting to use it (i.e. trying to "show" an entry results in "action aborted by user"). See screenshot below - top is in tmux, bottom is not, but both are in xterm:

https://i.imgur.com/VnMKMp0.jpg

**Comment by stevesbrain** [comment]
Okay, looks like I've found the solution @dominikschulz - thanks for assigning the labels :) The tmux config line in question that was causing issues was:

```bash
set -g default-terminal "screen-256color"
```

Which is interesting, because `screen` actually worked fine! But, adjusting that line to the following resolved the issue:

```bash
set -g default-terminal "rxvt-unicode-256color"
```

**Comment by Celti** [comment]
I just ran into this issue myself; changing the `TERM` variable will mask but not actually solve the problem (and can cause issues with other apps in your tmux sesssion).

The issue is with the new (breaking) changes to terminfo files for ncurses 6.1, which alters certain counts from 16-bit integers to 32-bit integers. This is pretty much only seen when you switch to a `-256color` version of a stock terminfo file — e.g., `TERM=tmux-256color` or `TERM=screen-256color` (`rxvt-unicode-256color` bypasses it by being a non-stock terminfo file built with an older ncurses version).

The solution has to go upstream to whatever gopass uses to render those TUI windows — I'm by no means a Go expert, but it looks like that's [jroimartin/gocui][1], which in turn depends on [nsf/termbox-go][2], which should have had this issue solved in commit https://github.com/nsf/termbox-go/commit/08476232a9953536788d8a9e6c6ddfe80ac73767. Perhaps something in gocui or gopass just needs to be told to use the newer revision?

[1]: https://github.com/jroimartin/gocui
[2]: https://github.com/nsf/termbox-go

**Comment by dominikschulz** [comment]
@Celti Thanks a lot for you research. That was super helpful!

I've updated the term UI related libraries in #789. Maybe someone can check if that fixes the problem?

**Comment by dominikschulz** [comment]
Amazing, thanks @Celti !
