### ISSUE TITLE
Windows binaries

### ISSUE THREAD

**Issue by bbigras** [justwatchcom/gopass#91]
Since Windows seems to be supported since #14 it would be nice to also have Windows binaries.

**Comment by metalmatze** [comment]
We currently support Windows "silently". We will have to do a lot more testing before releasing 1.1, since no one is running Windows here. 
If you like build the binary yourself. We would really appreciate feedback for Windows. Thanks!

**Comment by bbigras** [comment]
I got this error, not sure if I should open a new issue.

```
gpg: signing failed: secret key not available
error: gpg failed to sign the data
fatal: failed to write commit object
```

go version go1.8 windows/amd64
git version 2.12.1.windows.1 (with file caching and symlink support)
gopass fefd50587b8f922b973c7d83f3a880789223634d

**Comment by dominikschulz** [comment]
You can always open an issue if you feel like, then we can track any progress there.

That being said we currently have no timeline for windows support.

**Comment by majkinetor** [comment]
I created a [gist](https://gist.github.com/majkinetor/857a59ebbb43c6e687cf11d724209a21) that automates all of this on empty windows machine  This can be easily checked on AppVeyor.

The problem, however, is that gopass doesn't work. Here are the problems.

1. It creates the repository in the system root, not the `$HOME`
2. It can't add pass:
    ```
    PS:> gopass insert golang.org/gopher

    Error: Failed to stat stdin: GetFileInformationByHandle /dev/stdin: Incorrect function.
    ```

**Comment by AnomalRoil** [comment]
I've tested it on a Windows machine and also encountered the same error `Failed to stat stdin`, which I could solve by switching from Windows' `cmd` to Msys, as per what I've read on [this go issue](https://github.com/golang/go/issues/14853).

The next problem I encountered was with the path handling, the path has to the password store has to be specified with normal slashes "/" instead of windows' backslashes "\". However I was able to get it to work that way, copying to clipboard included.
The following seems to work:
```
config
help
show (works with normal slashes "/")
generate
move
copy
recipients
remove/delete
```
Note that for generate, etc. to work with a smartcard, I had to switch from gpg to gpg2 in `gpg.go` for gopass to work, and then I also had to force git to use gpg2 instead of gpg with a little:
`git config --global gpg.program gpg2 `, 
since it seems to try to auto-sign the git commits (since when???) and gpg wouldn't recognize the smartcard while gpg2 would.

The following wouldn't work, or was too buggy:
```
insert (won't do anything, just like if I had entered `cat` instead)
edit (won't open any editor, throwing an error)
completion (the command works, but even the bash from Msys won't autocomplete after sourcing it)
list (is actually not picking the structure correctly, it traces back the absolute path)
fsck (throwing a lot of error because of bugged structure and absolute paths)
find (is outputting Windows abs. path with wrong backslashes, so it won't work with show afterwards)
grep (trying to decrypt wrong abs. paths, unable to work, thus leads to "entry is not in the password-store" errors)
```

I didn't try the `mount` and other multi-store oriented feature, neither the git features, `clone` and `git`, for instance, because I'm not used to them.

I believe the edit and insert bugs are easily fixed, but didn't yet attempt to do so. (Basically they just need to call an editor correctly.)
However, the absolute path vs password-store path mess, as in the `list` command, is another thing... and I have no idea where to begin with that one.

**Comment by muesli** [comment]
This should already help us to identify a couple of Windows issues: https://ci.appveyor.com/project/muesli/gopass

**Comment by Zamiell** [comment]
Should we combine this with #334 ?

**Comment by dominikschulz** [comment]
We fixed to most obvious Windows issues and tests and provide Windows binaries for quite some time already.
